# Onedark (darker)
# Theme create by: https://github.com/devastion
# Update by(sort by time):
#
# Thanks for all contributor!!

# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "onedark"

# ========= Border =========
file_panel_border = "#5c6370"
sidebar_border = "#5c6370"
footer_border = "#5c6370"

# ========= Border Active =========
file_panel_border_active = "#848b98"
sidebar_border_active = "#848b98"
footer_border_active = "#848b98"
modal_border_active = "#868686"

# ========= Background (bg) =========
full_screen_bg = "#1f2329"
file_panel_bg = "#1f2329"
sidebar_bg = "#1f2329"
footer_bg = "#1f2329"
modal_bg = "#1f2329"

# ========= Foreground (fg) =========
full_screen_fg = "#a0a8b7"
file_panel_fg = "#a0a8b7"
sidebar_fg = "#a0a8b7"
footer_fg = "#a0a8b7"
modal_fg = "#a0a8b7"

# ========= Special Color =========
cursor = "#a0a8b7"
correct = "#98c379"
error = "#e86671"
hint = "#2b6f77"
cancel = "#993939"
# Gradient color can only have two color!
gradient_color = ["#61afef", "#382b2c"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#98c379"
file_panel_top_path = "#98c379"
file_panel_item_selected_fg = "#e5c07b"
file_panel_item_selected_bg = "#1f2329"

# ========= Sidebar Special Items =========
sidebar_title = "#98c379"
sidebar_item_selected_fg = "#e5c07b"
sidebar_item_selected_bg = "#1f2329"
sidebar_divider = "#5c6370"

# ========= Modal Special Items =========
modal_cancel_fg = "#e86671"
modal_cancel_bg = "#1f2329"

modal_confirm_fg = "#98c379"
modal_confirm_bg = "#1f2329"

# ========= Help Menu =========
help_menu_hotkey = "#d19a66"
help_menu_title = "#98c379"
