#!/usr/bin/env sh

# run command without password
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config \
  external_bar off:40:0 \
  menubar_opacity 0.9 \
  mouse_follows_focus off \
  focus_follows_mouse off \
  display_arrangement_order default \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow off \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 12 \
  bottom_padding 12 \
  left_padding 12 \
  right_padding 12 \
  window_gap 8 \
  layout bsp \
  mouse_modifier alt \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# focus window after active space changes
# yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
# yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after application is hidden
# yabai -m signal --add event=application_hidden action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after application is terminated
# yabai -m signal --add event=application_terminated action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after windows is destroyed
# yabai -m signal --add event=window_destroyed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after windows is minimized
# yabai -m signal --add event=window_minimized action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# disable yabai for these apps
yabai -m rule --add app="^Discord$" manage=off sub-layer=below
yabai -m rule --add app="^Mail$" manage=off sub-layer=auto
yabai -m rule --add app="^OrbStack$" manage=off sub-layer=auto
yabai -m rule --add app="^App Store$" manage=off sub-layer=auto
yabai -m rule --add app="^Calculator$" manage=off sub-layer=auto
yabai -m rule --add app="^Finder$" manage=off sub-layer=auto
yabai -m rule --add app="^Activity Monitor$" manage=off sub-layer=auto
yabai -m rule --add app="^Karabiner-Elements$" manage=off sub-layer=auto

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=4.0 &
