#!/usr/bin/env sh

# run command without password
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config \
  external_bar off:40:0 \
  menubar_opacity 0.9 \
  mouse_follows_focus off \
  focus_follows_mouse off \
  display_arrangement_order default \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow off \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 12 \
  bottom_padding 12 \
  left_padding 12 \
  right_padding 12 \
  window_gap 12 \
  layout bsp \
  mouse_modifier cmd \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action stack

# yabai -m config --space sm layout stack

# focus window after active space changes
# yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
# yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after application is hidden
# yabai -m signal --add event=application_hidden action="yabai -m window --focus recent"

# focus window after application is terminated
# yabai -m signal --add event=application_terminated action="yabai -m window --focus recent"

# focus window after windows is destroyed
# yabai -m signal --add event=window_destroyed action="yabai -m window --focus recent"

# focus window after windows is minimized
# yabai -m signal --add event=window_minimized action="yabai -m window --focus recent"

# yabai -m signal --add event=application_activated action="yabai -m window --raise"
# yabai -m signal --add event=application_deactivated action="yabai -m window --lower"


# disable yabai by default
yabai -m rule --add app=".*" manage=off sub-layer=below grid=6:6:1:1:4:4

# launch apps on proper space / display
yabai -m rule --add app="^iTerm2$" manage=on sub-layer=normal display=2
yabai -m rule --add app="^Brave Browser$" manage=on sub-layer=normal space=1
yabai -m rule --add app="^Alacritty$" manage=on sub-layer=normal
yabai -m rule --add app="^Code$" manage=on sub-layer=normal
yabai -m rule --add app="^Google Chrome$" manage=on sub-layer=normal space=2

