import = ["~/.config/alacritty/themes/onedark.toml"]
[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 5 }
dynamic_padding = true
decorations = "Buttonless"
option_as_alt = "OnlyLeft"
decorations_theme_variant = "Dark"

[scrolling]
history = 100000

[font]
normal.family = "JetbrainsMono Nerd Font Mono"
size = 16.0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
